# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Filipe Chaves
email: flschaves@gmail.com
author: Filipe Chaves
description: >- # this means to ignore newlines until "baseurl:"
  Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flschaves.com" # the base hostname & protocol for your site, e.g. http://example.com

# Social
social_links:
  twitter: flschaves
  github: flschaves
  instagram: flschaves
  wordpress_profile: flschaves

# Comments
disqus:
  shortname: flschaves

# SEO
google_analytics: UA-50383040-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: "post"
      is_post: true # automatically set is_post=true for all posts

host: 0.0.0.0

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
